---
title: Mark Ansell
author: Mark Ansell
email: markgansell@gmail.com
description: This website is modified from ubuild-jekyll, a Jekyll theme desgined
  to work with Forestry's Blocks feature. This theme provides a set of page-level
  components and a pre-configured Forestry Blocks UI that will empower content editors
  to construct their own webpages.
baseurl: ''
url: www.markansell.com
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
